export const SET_LOCALE = 'SET_LOCALE'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_ACCOUNT_IMAGE = 'SET_ACCOUNT_IMAGE'
export const SET_REFRESHED_TOKEN = 'SET_REFRESHED_TOKEN'

export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS'
export const SET_DOWNLOAD_PROGRESS = 'SET_DOWNLOAD_PROGRESS'
export const SET_OFFLINE = 'SET_OFFLINE'

export const UNSET_ACCOUNT = 'UNSET_ACCOUNT'

export const SET_USER_STATUS = 'SET_USER_STATUS'

export const SET_ALLOW_NAVIGATION = 'SET_ALLOW_NAVIGATION'

export const SET_MAIN_MENU = 'SET_MAIN_MENU'

export const SET_TOP_BAR_WIDGETS = 'SET_TOP_BAR_WIDGETS'

export const SET_PRODUCT_GROUPS = 'SET_PRODUCT_GROUPS'

export const SET_FOOTER_WIDGETS = 'SET_FOOTER_WIDGETS'

export const SET_SESSION_ID = 'SET_SESSION_ID'

export const LOCALE_COOKIE = 'wloc'
export const ACCOUNT_COOKIE = 'wacc'
export const PRODUCTS_LIST_VIEW_COOKIE = 'wplw'
export const CART_ID_COOKIE = 'wcid'
export const SESSION_COOKIE = 'wsid'
export const POPUP_COOKIE = 'wpop'

export const SET_OFFLINEMODE = 'SET_OFFLINEMODE'
export const SET_SETTINGS = 'SET_SETTINGS'

export const ADD_PRODUCT_TYPES = 'ADD_PRODUCT_TYPES'
export const SET_PRODUCTS_LIST_VIEW = 'SET_PRODUCTS_LIST_VIEW'

export const PRODUCTS_SET_COMPARE = 'PRODUCTS_SET_COMPARE'
export const PRODUCTS_COMPARE_ADD = 'PRODUCTS_COMPARE_ADD'
export const PRODUCTS_COMPARE_REMOVE = 'PRODUCTS_COMPARE_REMOVE'
export const PRODUCTS_COMPARE_COOKIE = 'wcp'

export const SET_CART_TOTAL_QUANTITY = 'SET_CART_TOTAL_QUANTITY'
export const SET_CART_ID = 'SET_CART_ID'
